const Portfolio_data = [
  {
    id: 1,
    category: "SCRUM MASTER",
    title: "The GoodTicket ",
    image: "./image/GoodTiket.png",
    text: "Criação de uma ferramenta inteligente em Aplicação Web com back-end com microserviços e front-end em single-page applications com Login completo, para atuar na identificação das causas de falhas que geram retrabalhos. Tal aplicação tem como ferramenta base de dados em NoSQL de registros anteriores, que causaram retrabalhos, já conhecidos.",
    url: 'https://github.com/annakks/Api-3dsm-2022',
  },
  {
    id: 2,
    category: "DEV APPLICATION MOBILE",
    title: "Coffee Copom",
    image: "./image/CoffeeCopom.png",
    text: "Criação de uma Aplicação Mobile para atuar no controle de intervalos de descanso dos Despachadores de Ocorrência do Copom de São Jose dos Campos.",
    url: "https://github.com/annakks/APP_Coffee_Front/tree/develop",
  },
  {
    id: 3,
    category: "DEV BACKEND",
    title: " Técnicas de Programação",
    image: "./image/Tecnicas.png",
    text: "Trata-se da criação de um Back-end para desenvolvimento uma agenda de clientes para o o Grupo World Beauty (WB). Cada unidade tem sua própria agenda, os dados não serão compartilhados entre as unidades do grupo WB. A agenda tem seguintes funcionalidades de cadastro: • CRUD (Create, Read, Update e Delete) de clientes; • CRUD de produtos ou serviços; • Registro de consumo dos produtos ou serviços que cada cliente adquiriu. ",
    url: "https://github.com/annakks/Trabalhos-de-Tecnicas-de-Programacao-1",
  },
  {
    id: 4,
    category: "BI",
    title: "Analise de Dados Eleitorais",
    image: "./image/Analise.png",
    text: "Criação de um site de análise de dados com a exibição de estatísticas do eleitorado localizado dentro de sua cobertura no Estado de São Paulo, podendo obter diversas características, como gráficos e tabelas de estado civil, escolaridade e faixa etária, além de informações sobre renda e evolução na quantidade de eleitores, tanto no âmbito municipal (de cada cidade) quanto macro-regiões, como o Vale do Paraíba.",
    url: "https://github.com/annakks/projeto-integrador-2021-1",
  },
  {
    id: 5,
    category: "DEV WEB",
    title: "DS Movie",
    image: "./image/DsMovie.png",
    text: "Projeto DS Movie, site elaborado na Semana Dev Superior com funcionalidade de enviar mensagens de texto para celular.",
    url: "https://github.com/annakks/sdmeta",
  },
  {
    id: 6,
    category: "DEV WEB",
    title: "Site Pessoal",
    image: "./image/Site.png",
    text: "Site Pessoal elaborado para as aula de Experiência do Usuário. ",
    url: "https://github.com/annakks/Annakks/tree/develop",
  },
]
export default Portfolio_data