name: DI /CD Deploy

on:
  push:
    branch: [develop]
  pull_request:
    branch: [develop]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout projeto
        uses: actions/checkout@v2

      - name: Config node
        uses: actions/setup-node@v2.2.0 
        with:
          node-version: 16

      - name: Instalação das depenencias
        run: npm install
      
  CD:
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Azure WebApp
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: AnnakksDevelop
          publish-profile: ${{ secrets.WEBAPP2 }}